"""Type stubs for gently - GentlyOS Python bindings"""

from typing import Tuple, List

class Lock:
    """The Lock - stays on device, NEVER transmitted"""
    def __init__(self, data: bytes) -> None: ...
    @staticmethod
    def random() -> Lock: ...
    def combine(self, key: Key) -> FullSecret: ...
    def to_bytes(self) -> bytes: ...
    def to_hex(self) -> str: ...

class Key:
    """The Key - can be stored anywhere (NFT, IPFS, etc.)"""
    def __init__(self, data: bytes) -> None: ...
    @staticmethod
    def from_hex(hex: str) -> Key: ...
    def to_bytes(self) -> bytes: ...
    def to_hex(self) -> str: ...
    def to_base64(self) -> str: ...

class FullSecret:
    """The Full Secret - exists only during Dance"""
    def __init__(self, data: bytes) -> None: ...
    def to_bytes(self) -> bytes: ...
    def sign(self, message: bytes) -> bytes: ...
    def verify(self, message: bytes, signature: bytes) -> bool: ...

class GenesisKey:
    """Genesis Key - root of all derivation"""
    @staticmethod
    def generate() -> GenesisKey: ...
    @staticmethod
    def from_seed(seed: str, salt: str) -> GenesisKey: ...
    def fingerprint(self) -> bytes: ...
    def derive(self, context: bytes) -> bytes: ...

class Pattern:
    """Visual/Audio pattern from hash"""
    @property
    def visual_name(self) -> str: ...
    @property
    def color_hex(self) -> str: ...
    @property
    def color_rgb(self) -> Tuple[int, int, int]: ...
    @property
    def shape(self) -> str: ...
    @property
    def motion(self) -> str: ...
    @property
    def frequency_hz(self) -> float: ...
    @property
    def chord(self) -> str: ...
    @property
    def rhythm(self) -> str: ...

def split_secret(secret: bytes) -> Tuple[Lock, Key]:
    """Split a 32-byte secret into Lock + Key pair"""
    ...

def encode_pattern(hash: bytes) -> Pattern:
    """Encode a 32-byte hash into a visual/audio pattern"""
    ...

def render_svg(pattern: Pattern, width: int = 400, height: int = 400) -> str:
    """Render a pattern to SVG string"""
    ...

def generate_decoys(pattern: Pattern, count: int = 3) -> List[str]:
    """Generate decoy patterns (similar but distinct) as SVG strings"""
    ...

def xor_bytes(a: bytes, b: bytes) -> bytes:
    """XOR two byte sequences of equal length"""
    ...
