#!/usr/bin/env bash
set -euo pipefail
#
# setup-dropbear.sh — Configure dropbear-initramfs for LUKS remote unlock.
#
# This script is designed to run ON the 3090 machine (via SSH from the Makefile).
# It installs and configures dropbear-initramfs so that you can SSH into the
# initramfs environment during boot to unlock LUKS-encrypted disks remotely.
#
# What it does:
#   1. Installs dropbear-initramfs
#   2. Configures dropbear to listen on port 2222
#   3. Copies authorized keys with restricted command prefix
#   4. Configures initramfs networking (DHCP)
#   5. Rebuilds the initramfs
#

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DROPBEAR_PORT=2222
DROPBEAR_CONF="/etc/dropbear/initramfs/dropbear.conf"
DROPBEAR_AUTH_KEYS="/etc/dropbear/initramfs/authorized_keys"
INITRAMFS_CONF="/etc/initramfs-tools/initramfs.conf"

# Authorized keys — these will be allowed to unlock LUKS.
# Each key is prefixed with restrictions so only cryptroot-unlock can run.
AUTHORIZED_KEYS=(
    # User's personal SSH key
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJM8FDlkumIPCkCLGA8Y+10800s35YSWw25Ml748FZVR tomlee3ddesign@gmail.com"
)

# Also include the generated 3090-headless key if provided via stdin or argument
# (The Makefile can pass additional keys as arguments)

# Key prefix that restricts what the SSH session can do in initramfs
KEY_PREFIX='no-port-forwarding,no-agent-forwarding,no-x11-forwarding,command="/bin/cryptroot-unlock"'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { printf '\033[1;34m[INFO]\033[0m  %s\n' "$*"; }
warn()  { printf '\033[1;33m[WARN]\033[0m  %s\n' "$*"; }
ok()    { printf '\033[1;32m[ OK ]\033[0m  %s\n' "$*"; }
err()   { printf '\033[1;31m[ERR ]\033[0m  %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------
preflight() {
    # Must run as root
    if [[ "$(id -u)" -ne 0 ]]; then
        err "This script must be run as root (use sudo)."
        exit 1
    fi

    # Must be on a system with LUKS
    if ! command -v cryptsetup &>/dev/null; then
        err "cryptsetup not found. Is LUKS encryption configured on this system?"
        exit 1
    fi

    # Check for LUKS devices
    if ! lsblk -o NAME,FSTYPE | grep -q "crypto_LUKS"; then
        warn "No LUKS-encrypted devices detected in lsblk."
        warn "This script is intended for systems with LUKS full-disk encryption."
        echo ""
        read -r -p "Continue anyway? [y/N] " answer
        case "${answer}" in
            [Yy]|[Yy][Ee][Ss]) ;;
            *) info "Aborted."; exit 0 ;;
        esac
    fi
}

# ---------------------------------------------------------------------------
# Install dropbear-initramfs
# ---------------------------------------------------------------------------
install_dropbear() {
    info "Installing dropbear-initramfs..."
    apt-get update -qq
    apt-get install -y dropbear-initramfs

    ok "dropbear-initramfs installed."
}

# ---------------------------------------------------------------------------
# Configure dropbear port and options
# ---------------------------------------------------------------------------
configure_dropbear() {
    info "Configuring dropbear to listen on port ${DROPBEAR_PORT}..."

    # Ensure the config directory exists
    mkdir -p "$(dirname "${DROPBEAR_CONF}")"

    # Write the dropbear configuration
    # -p sets the port, -s disables password login (key-only), -j disables local port forwarding,
    # -k disables remote port forwarding, -I sets idle timeout to 180 seconds
    cat > "${DROPBEAR_CONF}" <<EOF
# dropbear-initramfs configuration for LUKS remote unlock
# Generated by setup-dropbear.sh on $(date -Iseconds)
DROPBEAR_OPTIONS="-p ${DROPBEAR_PORT} -s -j -k -I 180"
EOF

    ok "Dropbear configured on port ${DROPBEAR_PORT} (key-only auth)."
}

# ---------------------------------------------------------------------------
# Set up authorized keys with restricted prefix
# ---------------------------------------------------------------------------
setup_authorized_keys() {
    info "Setting up authorized keys for LUKS unlock..."

    # Ensure the directory exists
    mkdir -p "$(dirname "${DROPBEAR_AUTH_KEYS}")"

    # Start with an empty file
    : > "${DROPBEAR_AUTH_KEYS}"

    # Add each authorized key with the restricted command prefix
    for key in "${AUTHORIZED_KEYS[@]}"; do
        echo "${KEY_PREFIX} ${key}" >> "${DROPBEAR_AUTH_KEYS}"
        # Show a truncated version of the key for confirmation
        local key_short
        key_short="$(echo "${key}" | awk '{print $1 " " substr($2,1,20) "..." " " $3}')"
        ok "  Added: ${key_short}"
    done

    # If the generated 3090-headless.pub key exists on this machine or was
    # passed as an argument, add it too
    for arg in "$@"; do
        if [[ -f "${arg}" ]]; then
            # It's a file path — read the key from the file
            while IFS= read -r key; do
                [[ -z "${key}" || "${key}" =~ ^# ]] && continue
                echo "${KEY_PREFIX} ${key}" >> "${DROPBEAR_AUTH_KEYS}"
                local key_short
                key_short="$(echo "${key}" | awk '{print $1 " " substr($2,1,20) "..." " " $3}')"
                ok "  Added: ${key_short}"
            done < "${arg}"
        elif [[ "${arg}" =~ ^ssh- ]]; then
            # It's a raw key string
            echo "${KEY_PREFIX} ${arg}" >> "${DROPBEAR_AUTH_KEYS}"
            local key_short
            key_short="$(echo "${arg}" | awk '{print $1 " " substr($2,1,20) "..." " " $3}')"
            ok "  Added: ${key_short}"
        fi
    done

    # Set permissions
    chmod 600 "${DROPBEAR_AUTH_KEYS}"

    local key_count
    key_count="$(grep -c '^no-port' "${DROPBEAR_AUTH_KEYS}" || echo 0)"
    ok "${key_count} authorized key(s) configured for LUKS unlock."
}

# ---------------------------------------------------------------------------
# Configure initramfs networking
# ---------------------------------------------------------------------------
configure_initramfs_network() {
    info "Configuring initramfs networking (DHCP)..."

    # Back up original config
    if [[ -f "${INITRAMFS_CONF}" ]]; then
        cp "${INITRAMFS_CONF}" "${INITRAMFS_CONF}.bak.$(date +%Y%m%d%H%M%S)"
        ok "Backed up ${INITRAMFS_CONF}"
    fi

    # Check if IP= is already set
    if grep -qE '^IP=' "${INITRAMFS_CONF}" 2>/dev/null; then
        # Replace existing IP= line
        sed -i 's/^IP=.*/IP=dhcp/' "${INITRAMFS_CONF}"
        ok "Updated existing IP= directive to IP=dhcp"
    else
        # Append IP=dhcp
        echo "" >> "${INITRAMFS_CONF}"
        echo "# Enable DHCP networking in initramfs for dropbear remote unlock" >> "${INITRAMFS_CONF}"
        echo "IP=dhcp" >> "${INITRAMFS_CONF}"
        ok "Added IP=dhcp to ${INITRAMFS_CONF}"
    fi
}

# ---------------------------------------------------------------------------
# Update initramfs
# ---------------------------------------------------------------------------
update_initramfs() {
    info "Rebuilding initramfs (this may take a moment)..."
    update-initramfs -u -v 2>&1 | tail -5
    ok "Initramfs updated successfully."
}

# ---------------------------------------------------------------------------
# Print instructions
# ---------------------------------------------------------------------------
print_instructions() {
    local ip
    ip="$(hostname -I | awk '{print $1}')"

    echo ""
    echo "==========================================="
    echo "  DROPBEAR REMOTE UNLOCK CONFIGURED"
    echo "==========================================="
    echo ""
    echo "On reboot, the system will pause at LUKS unlock."
    echo "Dropbear SSH will be listening on port ${DROPBEAR_PORT}."
    echo ""
    echo "To unlock LUKS remotely:"
    echo ""
    echo "  1. SSH into the initramfs environment:"
    echo ""
    echo "     ssh -p ${DROPBEAR_PORT} root@${ip}"
    echo ""
    echo "  2. Type your LUKS passphrase when prompted."
    echo "     The system will continue booting after unlock."
    echo ""
    echo "  3. Then SSH to port 22 as normal:"
    echo ""
    echo "     ssh zero20nez@${ip}"
    echo ""
    echo "==========================================="
    echo ""
    echo "IMPORTANT NOTES:"
    echo "  - Dropbear uses port ${DROPBEAR_PORT} (not 22)"
    echo "  - You connect as 'root' to dropbear (not your user)"
    echo "  - Only key-based auth is allowed (no passwords)"
    echo "  - The SSH session only runs cryptroot-unlock"
    echo "  - Host keys WILL differ from the normal SSH server"
    echo "    (use a separate known_hosts or -o UserKnownHostsFile)"
    echo ""
    echo "Example unlock script for your workstation:"
    echo ""
    echo "  ssh -p ${DROPBEAR_PORT} -o StrictHostKeyChecking=no \\"
    echo "      -o UserKnownHostsFile=/dev/null root@${ip}"
    echo ""
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    info "Dropbear-initramfs Setup for LUKS Remote Unlock"
    info "Running on: $(hostname) ($(hostname -I | awk '{print $1}'))"
    echo ""

    preflight
    install_dropbear
    configure_dropbear
    setup_authorized_keys "$@"
    configure_initramfs_network
    update_initramfs
    print_instructions

    ok "Setup complete. Reboot to test remote LUKS unlock."
}

main "$@"
